# Generated by Django 4.2.2 on 2023-06-15 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negResult', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Desire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fearName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obstruction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penName', models.CharField(max_length=25)),
                ('profilePic', models.URLField(default='https://static.vecteezy.com/system/resources/thumbnails/009/734/564/small/default-avatar-profile-icon-of-social-media-user-vector.jpg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.character')),
                ('consequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.consequence')),
                ('desire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.desire')),
                ('fear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.fear')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.genre')),
                ('obstacles', models.ManyToManyField(related_name='seed_obstacles', to='storylabapi.obstacle')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.reward')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.writer')),
            ],
        ),
    ]
