# Generated by Django 4.2.2 on 2023-06-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storylabapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.genre'),
        ),
    ]
