# Generated by Django 4.2.2 on 2023-06-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storylabapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('prose', models.CharField(max_length=50)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storylabapi.writer')),
            ],
        ),
    ]
