# Generated by Django 4.2.2 on 2023-06-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storylabapi', '0002_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='prose',
            field=models.CharField(max_length=1200),
        ),
    ]
