# Generated by Django 4.2.2 on 2023-06-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storylabapi', '0002_alter_seed_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='userName',
        ),
    ]
